server:
  port: 8761

encrypt:
  failOnError: false

security:
  basic:
    enabled: false
  user:
    name: user
    password: 123456

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  instance:
    hostname: discovery
    metadata-map:
          user:
            name: user
            password: 123456
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

spring:
  cloud:
    config:
      discovery: 
        enabled: true
